### ISSUE TITLE
missing lib linkage

### ISSUE THREAD

**Issue by r-lyeh** [septag/glslcc#1]
Hey @septag 

Just trying to compile your tool :D

It gave following error when linking:
`  sxd.lib(os.obj) : error LNK2019: unresolved external symbol _GetProcessMemoryInfo@12 referenced in function _sx_os_processmem [glslcc\.build\src\glslcc.vcxproj]`

So I added  `#pragma comment(lib, "psapi.lib")` somewhere to fix it :)

PS: Suggestion: what about providing binary releases?

**Comment by septag** [comment]
Thanks, fixed it in cmake file.
and yes I'll put a binary as soon as it gets relatively stable

**Comment by r-lyeh** [comment]
Fixed!
