### ISSUE TITLE
samples failed to cross-compile

### ISSUE THREAD

**Issue by r-lyeh** [septag/glslcc#2]
Hey again,
Just used your own samples and they refused to work:

```
> glslcc --vert=shader.vert --frag=shader.frag --output=shader.hlsl --lang=hlsl --reflect
ERROR: sample.vert:5: '' : vertex input cannot be further qualified
ERROR: sample.vert:5: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```

**Comment by septag** [comment]
could you send me the _sample.vert_ ?
I have tried it myself, and it compiles...  also pushed the new 1.2.2 version.
you can also try with this command to see the preprocessed file:

```
glslcc --vert=shader.vert --preprocess
```

**Comment by r-lyeh** [comment]
yup, i will send you some more info in a few hours!

**Comment by r-lyeh** [comment]
I cloned the repo again, used the very same sources from the README and now it works ¯\_(ツ)_/¯
PS: no idea about what sample.vert was! ¯\_(ツ)_/¯
