### ISSUE TITLE
How to handle in cross manier stage binding

### ISSUE THREAD

**Issue by amerkoleci** [septag/glslcc#3]
Hi,

Excellent job on library, I'm working on personal game engine and come to your shader compiler, I added the HLSL stage semantics support (POSITION, COLOR0 etc) and it fits well.

Question is,
How you handle shader bindings? While vulkan has set and binding for uniform buffers, samplers etc, HLSL and DirectX has stage binding, do you plan to add some schema/trick for this part as well?

Thanks

**Comment by septag** [comment]
thanks
I guess I didn't get your question clearly, what do you mean by HLSL's stage binding? do you mean ```register(t0..N)``` for textures ?

**Comment by amerkoleci** [comment]
Vulkan has layout (binding = 1, set 1) uniform sampler2D mySampler; while hlsl has registers without the set.
