### ISSUE TITLE
parse_output_log() early-outs after finding the first non-error and fails to output further errors

### ISSUE THREAD

**Issue by Weaseltron** [septag/glslcc#6]
I've just started using the codebase so apologies if I'm missing something, but consider the following code in glslcc.cpp:

`static bool parse_output_log(const char* str, std::vector<output_parse_result>* r)
{
    const char* header = "ERROR: ";
    while (sx_strstr(str, header) == str) {
        str += sx_strlen(header);
        const char* divider = sx_strchar(str, ':');
<snip>
        r->push_back(lr);
    }
    return true;
}`

In my shader, the first output message in str is a "WARNING: ", not an "ERROR: ". The result appears to be that we write nothing to the output_parse_result vector as we only parse the array as far as the first non-error message and all further messages are ignored.

**Comment by Iainmon** [comment]
Same issue here I think. Just started using the CLI. I get a non-zero exit code when trying to compile the examples with any of the sample commands.

**Comment by Iainmon** [comment]
Just got it working. I switched to v1.62.0

**Comment by Iainmon** [comment]
Well that sucks because "fixed a bug with GLSL headers (#version)" was patched in the latest version.

**Comment by septag** [comment]
sorry for late reply.
could you provide an example for your case ? because I can't reproduce this
