### ISSUE TITLE
Mat4 attribute when targeting MSL results in attributes being used more than once

### ISSUE THREAD

**Issue by zacharycarter** [septag/glslcc#9]
I have the following vertex shader inputs -

layout (location = 0) in vec3 a_position;
layout (location = 1) in vec3 a_normal;
layout (location = 2) in vec4 a_color;
layout (location = 3) in mat4 joint;
Using glslang to produce SPIR-V and then invoking SPIRV-cross targeting metal, the following MSL is produced -

struct main0_in
{
    float4 joint_0 [[attribute(0)]];
    float4 joint_1 [[attribute(1)]];
    float3 a_position [[attribute(1)]];
    float4 joint_2 [[attribute(2)]];
    float3 a_normal [[attribute(2)]];
    float4 joint_3 [[attribute(3)]];
    float4 a_color [[attribute(3)]];
};

Which produces the following error when the msl is compiled -

error: 'attribute' index '1' is used more than once
I tried setting joint to location 0 and position, normal and color to 4 5 and 6 respectively, but the same code was generated.

Am I doing something wrong here, or is this a legitimate issue?

**Comment by septag** [comment]
hm.. it's generally recommended to not use matrix type as vertex input because of register allocation and just use multiple vectors. but this is also weird, have to dig deeper, but maybe a glslang or spirv-tools bug as well.

anyway, I changed your mat4 to 4 vectors:
```
layout (location = 0) in vec3 a_position;
layout (location = 1) in vec3 a_normal;
layout (location = 2) in vec4 a_color;
layout (location = 3) in vec4 joint_1;
layout (location = 4) in vec4 joint_2;
layout (location = 5) in vec4 joint_3;
layout (location = 6) in vec4 joint_4;
```

and the output is now correct:
```
struct main0_in
{
    float4 joint_1 [[attribute(0)]];
    float4 joint_2 [[attribute(1)]];
    float4 joint_3 [[attribute(2)]];
    float4 joint_4 [[attribute(3)]];
    float3 a_position [[attribute(4)]];
    float3 a_normal [[attribute(5)]];
    float4 a_color [[attribute(6)]];
};
```
